# This playbook is intended before chrooting into the installation.
# * the chroot is expected to be already mounted in `/mnt`
# * network connection already established
# * Ansible installed (pacman -S ansible)
---
- name: Preflight
  hosts: laptops
  tasks:

    - name: Pacstrap /mnt
      community.general.pacman:
        name:
          - ansible
          - base
          - base-devel
          - linux
          - linux-firmware
          - man-db
          - sof-firmware
          - sudo
          - xfsprogs
        state: present
        root: /mnt
        cachedir: /mnt/var/cache/pacman/pkg
        update_cache: true

    - name: Check /etc/fstab
      ansible.builtin.stat:
        path: /mnt/etc/fstab
        checksum_algorithm: sha256
      register: _fstab

    - name: Generate /etc/fstab
      ansible.builtin.shell:
        cmd: genfstab -U /mnt >> /mnt/etc/fstab
      when: _fstab.stat.checksum == "e54626e74ed8fee4173b62a545ab1c3a3a069e4217a0ee8fc398d9933e9c1696"
