# This playbook is intended before chrooting into the installation.
# * the chroot is expected to be already mounted in `/mnt`
# * network connection already established
# * Ansible installed
---
- name: Preflight
  hosts: laptops
  tasks:
    - name: Update Pacman Cache
      community.general.pacman:
        update_cache: true

    - name: Pacstrap /mnt
      community.general.pacman:
        name:
          - ansible
          - base
          - base-devel
          - linux
          - linux-firmware
          - intel-ucode
          - man-db
          - sof-firmware
          - sbctl
          - vim
          - xfsprogs

    - name: Check /etc/fstab
      ansible.builtin.stat:
        path: /mnt/etc/fstab
        checksum_algorithm: sha256
      register: fstab

    - name: Generate /etc/fstab
      ansible.builtin.shell:
        cmd: genfstab -U /mnt >> /mnt/etc/fstab
      when: fstab.stat.checksum == "e54626e74ed8fee4173b62a545ab1c3a3a069e4217a0ee8fc398d9933e9c1696"