---
- name: Rollout
  hosts: laptops
  become: true
  tasks:

    - name: Update Pacman Cache
      community.general.pacman:
        update_cache: true
      changed_when: false

    - name: Configure baseline
      ansible.builtin.include_tasks:
        file: "{{ playbook_dir }}/tasks/pacman.yaml"
      when: baseline_execute

    - name: Configure modprobe
      ansible.builtin.include_tasks:
        file: "{{ playbook_dir }}/tasks/modprobe.yaml"

    - name: Configure Shell
      ansible.builtin.include_tasks:
        file: "{{ playbook_dir }}/tasks/shell.yaml"

    - name: Configure Tools
      ansible.builtin.include_tasks:
        file: "{{ playbook_dir }}/tasks/tools.yaml"

    - name: Configure fwupd
      ansible.builtin.include_tasks:
        file: "{{ playbook_dir }}/tasks/fwupd.yaml"

    - name: Configure Secure Boot
      ansible.builtin.include_tasks:
        file: "{{ playbook_dir }}/tasks/secureboot.yaml"
      when: secureboot_execute

    - name: Configure mkinitcpio
      ansible.builtin.include_tasks:
        file: "{{ playbook_dir }}/tasks/mkinitcpio.yaml"

    - name: Configure pacman
      ansible.builtin.include_tasks:
        file: "{{ playbook_dir }}/tasks/pacman.yaml"

    - name: Configure systemd
      ansible.builtin.include_tasks:
        file: "{{ playbook_dir }}/tasks/systemd.yaml"

    - name: Configure GNOME Desktop Environment
      ansible.builtin.include_tasks:
        file: "{{ playbook_dir }}/tasks/gnome.yaml"

    - name: Configure Intel
      ansible.builtin.include_tasks:
        file: "{{ playbook_dir }}/tasks/intel.yaml"
      when: "'Intel' in ansible_facts['processor'] | join(' ')"

    - name: Configure BlueZ
      ansible.builtin.include_tasks:
        file: "{{ playbook_dir }}/tasks/bluez.yaml"

    - name: Configure NetworkManager
      ansible.builtin.include_tasks:
        file: "{{ playbook_dir }}/tasks/networkmanager.yaml"

    - name: Configure udev
      ansible.builtin.include_tasks:
        file: "{{ playbook_dir }}/tasks/udev.yaml"

  handlers:

    - name: Reload udev
      ansible.builtin.shell:
        cmd: udevadm control --reload-rules

    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Run mkinitcpio
      ansible.builtin.shell:
        cmd: mkinitcpio -P

    - name: Reminder root password
      ansible.builtin.debug:
        msg: "REMINDER: Do not forget to set a root password!"
