---
- name: Install firewalld
  community.general.pacman:
    name: firewalld
    state: present

- name: Install firewalld Optionals
  community.general.pacman:
    name: firewall-config
    state: present
    reason: dependency

- name: Configure /etc/firewalld/zones
  ansible.builtin.file:
    path: /etc/firewalld/zones
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Configure /etc/firewalld/zones/*.zones
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/etc/firewalld/zones/{{ item | basename | regex_replace('\\.j2', '') }}"
    owner: root
    group: root
    mode: "0644"
  loop: "{{ lookup('fileglob', playbook_dir + '/templates/firewalld/zones/*.xml.j2', wantlist=True) }}"

- name: Configure /etc/pacman.d/hooks/60-firewalld.hook
  ansible.builtin.template:
    src: "{{ playbook_dir }}/templates/firewalld/firewalld.hook.j2"
    dest: /etc/pacman.d/hooks/60-firewalld.hook
    owner: root
    group: root
    mode: "0644"

- name: Enable firewalld
  ansible.builtin.systemd:
    name: firewalld.service
    enabled: true
