---
- name: Install GNOME
  community.general.pacman:
    name:
      - baobab
      - cups
      - easyeffects
      - evolution
      - file-roller
      - firewalld
      - gdm
      - ghostty
      - gimp
      - gnome-backgrounds
      - gnome-calculator
      - gnome-clocks
      - gnome-color-manager
      - gnome-control-center
      - gnome-font-viewer
      - gnome-keyring
      - gnome-session
      - gnome-settings-daemon
      - gnome-shell
      - gnome-system-monitor
      - gnome-text-editor
      - gnome-tweaks
      - gnome-user-docs
      - gnome-weather
      - gvfs
      - loupe
      - nautilus
      - papers
      - pdfarranger
      - pipewire
      - plymouth
      - power-profiles-daemon
      - quodlibet
      - seahorse
      - shotwell
      - simple-scan
      - snapshot
      - sound-juicer
      - soundconverter
      - wireplumber
      - xdg-desktop-portal-gnome
      - xdg-user-dirs-gtk
    state: present

- name: Install GNOME Optionals
  community.general.pacman:
    name:
      - calf
      - gnome-shell-extensions
      - gnome-shell-extension-dash-to-panel
      - gst-libav
      - gst-plugins-bad
      - gst-plugins-ugly
      - gvfs-afc
      - gvfs-mtp
      - gvfs-nfs
      - gvfs-smb
      - lsp-plugins-lv2
      - mda.lv2
      - zam-plugins-lv2
    state: present
    reason: dependency

- name: Enable GDM
  ansible.builtin.systemd:
    name: gdm.service
    enabled: true

- name: Install Plymouth Themes
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/templates/gnome/plymouth-themes/"
    dest: /usr/share/plymouth/themes/
    owner: root
    group: root
    mode: "0644"
    directory_mode: "0755"

- name: Configure Plymouth
  ansible.builtin.copy:
    content: |
      # Administrator customizations go in this file
      [Daemon]
      Theme=arch-glow
    dest: /etc/plymouth/plymouthd.conf
    owner: root
    group: root
    mode: "0644"
  notify: Run mkinitcpio
