---
- name: Install GNOME
  community.general.pacman:
    name:
      - baobab
      - gdm
      - gnome-backgrounds
      - gnome-calculator
      - gnome-clocks
      - gnome-color-manager
      - gnome-control-center
      - gnome-font-viewer
      - gnome-keyring
      - gnome-session
      - gnome-settings-daemon
      - gnome-shell
      - gnome-system-monitor
      - gnome-text-editor
      - gnome-user-docs
      - gnome-weather
      - gvfs
      - loupe
      - nautilus
      - papers
      - simple-scan
      - snapshot
      - xdg-desktop-portal-gnome
      - xdg-user-dirs-gtk
      - networkmanager
      - bluez
      - fwupd
    state: present

- name: Install GNOME Optionals
  community.general.pacman:
    name:
      - gvfs-afc
      - gvfs-mtp
      - gvfs-nfs
      - gvfs-smb
      - bluez-utils
    state: present
    reason: dependency

- name: Enable GDM
  ansible.builtin.systemd:
    name: gdm.service
    enabled: true
