---
- name: Install GNOME
  community.general.pacman:
    name:
      - adobe-source-code-pro-fonts
      - adobe-source-han-sans-otc-fonts
      - adobe-source-sans-fonts
      - adobe-source-serif-fonts
      - baobab
      - bitwarden
      - cups
      - easyeffects
      - evolution
      - file-roller
      - fprintd
      - gdm
      - gimp
      - gnome-backgrounds
      - gnome-calculator
      - gnome-clocks
      - gnome-color-manager
      - gnome-control-center
      - gnome-font-viewer
      - gnome-keyring
      - gnome-session
      - gnome-settings-daemon
      - gnome-shell
      - gnome-system-monitor
      - gnome-text-editor
      - gnome-tweaks
      - gnome-user-docs
      - gnome-weather
      - gvfs
      - hplip
      - loupe
      - nautilus
      - obsidian
      - papers
      - papirus-icon-theme
      - pdfarranger
      - pipewire
      - plymouth
      - power-profiles-daemon
      - quodlibet
      - seahorse
      - shotwell
      - simple-scan
      - snapshot
      - sound-juicer
      - soundconverter
      - ttf-bitstream-vera
      - ttf-croscore
      - ttf-dejavu
      - ttf-hack-nerd
      - ttf-ibm-plex
      - ttf-ibmplex-mono-nerd
      - ttf-iosevka-nerd
      - ttf-iosevkaterm-nerd
      - ttf-jetbrains-mono
      - ttf-jetbrains-mono-nerd
      - ttf-mona-sans
      - ttf-nunito
      - ttf-sourcecodepro-nerd
      - vlc-plugin-dvd
      - vlc-plugin-ffmpeg
      - vlc-plugin-freetype
      - vlc-plugin-gstreamer
      - vlc-plugin-mad
      - vlc-plugin-mdns
      - vlc-plugin-mpeg2
      - vlc-plugin-samplerate
      - vlc-plugin-x264
      - vlc-plugin-x265
      - wireplumber
      - xdg-desktop-portal-gnome
      - xdg-user-dirs-gtk
    state: present

- name: Install GNOME Optionals
  community.general.pacman:
    name:
      - calf
      - gnome-shell-extensions
      - gnome-shell-extension-dash-to-panel
      - gst-libav
      - gst-plugins-bad
      - gst-plugins-ugly
      - gvfs-afc
      - gvfs-mtp
      - gvfs-nfs
      - gvfs-smb
      - lsp-plugins-lv2
      - mda.lv2
      - sassc
      - zam-plugins-lv2
    state: present
    reason: dependency

- name: Enable GDM
  ansible.builtin.systemd:
    name: gdm.service
    enabled: true

- name: Enable CUPS
  ansible.builtin.systemd:
    name: cups.service
    enabled: true

- name: Enable power-profiles-daemon
  ansible.builtin.systemd:
    name: power-profiles-daemon.service
    enabled: true

- name: Install Plymouth Themes
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/templates/gnome/plymouth-themes/"
    dest: /usr/share/plymouth/themes/
    owner: root
    group: root
    mode: "0644"
    directory_mode: "0755"

- name: Configure Plymouth
  ansible.builtin.template:
    src: "{{ playbook_dir }}/templates/gnome/plymouthd.conf.j2"
    dest: /etc/plymouth/plymouthd.conf
    owner: root
    group: root
    mode: "0644"
  notify: Run mkinitcpio

- name: Check Colloid-Theme
  ansible.builtin.stat:
    path: /usr/share/themes/Colloid-Dark
  register: _gnome_theme_location

- name: Install Colloid-Theme
  block:

    - name: Create temporary dir
      ansible.builtin.tempfile:
        state: directory
      changed_when: false
      register: _gnome_theme_tmp

    - name: GNOME clone source
      ansible.builtin.git:
        repo: https://github.com/vinceliuice/Colloid-gtk-theme.git
        dest: "{{ _gnome_theme_tmp.path }}"
      changed_when: false

    - name: Remove Colloid-Theme
      ansible.builtin.shell:
        chdir: "{{ _gnome_theme_tmp.path }}"
        cmd: ./install.sh -r
        executable: /usr/bin/bash
      when: gnome_theme_force_latest

    - name: Install Colloid-Theme
      ansible.builtin.shell:
        chdir: "{{ _gnome_theme_tmp.path }}"
        cmd: >
          ./install.sh
          --tweaks rimless
          --tweaks normal
          --tweaks black
          -s standard
          -c dark
          -d /usr/share/themes
        executable: /usr/bin/bash

  always:

    - name: GNOME cleanup temporary dir
      ansible.builtin.file:
        path: "{{ _gnome_theme_tmp.path }}"
        state: absent
      changed_when: false

  when: _gnome_theme_location.stat.isdir is not defined or gnome_theme_force_latest

- name: Configure /etc/skel/.config/environment.d
  ansible.builtin.file:
    path: /etc/skel/.config/environment.d
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Configure /etc/skel/.config/environment.d/gcr.conf
  ansible.builtin.template:
    src: "{{ playbook_dir }}/templates/gnome/gcr.conf.j2"
    dest: /etc/skel/.config/environment.d/gcr.conf
    owner: root
    group: root
    mode: "0644"

- name: Configure /etc/skel/.config/environment.d/gtk.conf
  ansible.builtin.template:
    src: "{{ playbook_dir }}/templates/gnome/gtk.conf.j2"
    dest: /etc/skel/.config/environment.d/gtk.conf
    owner: root
    group: root
    mode: "0644"
