---
- name: Install intel-ucode
  community.general.pacman:
    name: intel-ucode
    state: present
  notify: Run mkinitcpio

- name: Install thermald
  community.general.pacman:
    name: thermald
    state: present

- name: Configure /etc/systemd/system/thermald.service.d
  ansible.builtin.file:
    path: /etc/systemd/system/thermald.service.d
    state: directory
    owner: root
    group: root
    mode: "0755"
  when: >-
    (thermald_systemd_service_overwrite is defined) and
    (thermald_systemd_service_overwrite | length > 0)

- name: Configure /etc/systemd/system/thermald.service.d/overwrite.conf
  ansible.builtin.copy:
    content: "{{ thermald_systemd_service_overwrite }}"
    dest: /etc/systemd/system/thermald.service.d/overwrite.conf
    owner: root
    group: root
    mode: "0644"
  notify: Reload systemd
  when: >-
    (thermald_systemd_service_overwrite is defined) and
    (thermald_systemd_service_overwrite | length > 0)

- name: Enable thermald
  ansible.builtin.systemd:
    name: thermald.service
    enabled: true

- name: Install intel-lpmd
  community.general.pacman:
    name: intel-lpmd
    state: present

- name: Enable intel-lpmd
  ansible.builtin.systemd:
    name: intel_lpmd.service
    enabled: true

- name: Install vpl-gpu-rt
  community.general.pacman:
    name: vpl-gpu-rt
    state: present

- name: Install vulkan-intel
  community.general.pacman:
    name: vulkan-intel
    state: present

- name: Extract GPU PCI ID
  ansible.builtin.shell:
    cmd: lspci -nnd ::03xx
  register: intel_pci
  changed_when: False
  when: intel_use_xe | default(False)

- name: Configure /etc/modprobe.d/intel.conf
  ansible.builtin.template:
    src: "{{ playbook_dir }}/templates/modprobe/intel.conf.j2"
    dest: /etc/modprobe.d/intel.conf
    owner: root
    group: root
    mode: "0644"
  when: intel_use_xe
  
- name: Remove /etc/modprobe.d/intel.conf
  ansible.builtin.file:
    src: /etc/modprobe.d/intel.conf
    state: absent
  when: intel_use_xe == False