---
- name: Configure /etc/mkinitcpio.conf
  ansible.builtin.template:
    src: "{{ playbook_dir }}/templates/mkinitcpio/mkinitcpio.conf.j2"
    dest: /etc/mkinitcpio.conf
    owner: root
    group: root
    mode: "0644"
  notify: Run mkinitcpio

- name: Configure /etc/mkinitcpio.d
  ansible.builtin.file:
    path: /etc/mkinitcpio.d
    state: directory
    owner: root
    group: root
    mode: "0755"

# Use UKI instead of the default image.
- name: Configure /etc/mkinitcpio.d/linux.preset
  ansible.builtin.template:
    src: "{{ playbook_dir }}/templates/mkinitcpio/linux.preset.j2"
    dest: /etc/mkinitcpio.d/linux.preset
    owner: root
    group: root
    mode: "0644"
  notify: Run mkinitcpio

- name: Configure /etc/kernel/cmdline
  ansible.builtin.template:
    src: "{{ playbook_dir }}/templates/mkinitcpio/cmdline.j2"
    dest: /etc/kernel/cmdline
    owner: root
    group: root
    mode: "0644"
  notify: Run mkinitcpio

- name: Show Kernel cmdline rd.luks.name
  ansible.builtin.debug:
    msg: "rd.luks.name={{ ansible_facts.devices[luks_device].partitions[luks_partition].uuid }}=root"
  when: mkinitcpio_luks
