---
- name: Configure /etc/mkinitcpio.conf
  ansible.builtin.template:
    src: "{{ playbook_dir }}/templates/mkinitcpio/mkinitcpio.conf.j2"
    dest: /etc/mkinitcpio.conf
    owner: root
    group: root
    mode: "0644"
  notify: Run mkinitcpio
