---
- name: Install NetworkManager
  community.general.pacman:
    name: networkmanager
    state: present

- name: Install ModemManager
  community.general.pacman:
    name: modemmanager
    state: present
    reason: dependency

- name: Install iwd
  community.general.pacman:
    name: iwd
    state: present
    reason: dependency

- name: Configure /etc/NetworkManager/conf.d
  ansible.builtin.file:
    path: /etc/NetworkManager/conf.d
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Configure /etc/NetworkManager/conf.d/wifi_backend.conf
  ansible.builtin.copy:
    content: |
      [device]
      wifi.backend=iwd
    dest: /etc/NetworkManager/conf.d/wifi_backend.conf
    owner: root
    group: root
    mode: "0644"

- name: Configure /etc/conf.d/wireless-regdom
  ansible.builtin.lineinfile:
    path: /etc/conf.d/wireless-regdom
    regexp: '^#WIRELESS_REGDOM="{{ wireless_regdom | upper }}"'
    line: 'WIRELESS_REGDOM="{{ wireless_regdom | upper }}"'
    owner: root
    group: root
    mode: '0644'

- name: Enable NetworkManager
  ansible.builtin.systemd:
    name: NetworkManager.service
    enabled: true

- name: Enable ModemManager
  ansible.builtin.systemd:
    name: ModemManager.service
    enabled: true
