---
- name: Install NetworkManager
  community.general.pacman:
    name: networkmanager
    state: present

- name: Install NetworkManager Optionals
  community.general.pacman:
    name: modemmanager
    state: present
    reason: dependency

- name: Enable NetworkManager
  ansible.builtin.systemd:
    name: NetworkManager.service
    enabled: true

- name: Enable ModemManager
  ansible.builtin.systemd:
    name: ModemManager.service
    enabled: true
