---
- name: Install sbctl
  community.general.pacman:
    name: sbctl
    state: present

- name: Configure /etc/keys/secureboot
  ansible.builtin.file:
    path: /etc/keys/secureboot
    state: directory
    owner: root
    group: root
    mode: "0750"

- name: Copy /etc/keys/secureboot
  ansible.builtin.copy:
    content: "{{ item.value }}"
    dest: "/etc/keys/secureboot/{{ item.name }}"
    owner: root
    group: root
    mode: "0440"
    checksum: "{{ item.sha1sum }}"
  loop: "{{ secureboot_files }}"
  register: _secureboot_keys
  become: true

- name: Import /etc/keys/secureboot
  ansible.builtin.shell:
    cmd: >-
      sbctl import-keys
      --db-cert /etc/keys/secureboot/db.crt
      --db-key /etc/keys/secureboot/db.key
      --kek-cert /etc/keys/secureboot/KEK.crt
      --kek-key /etc/keys/secureboot/KEK.key
      --pk-cert /etc/keys/secureboot/PK.crt
      --pk-key /etc/keys/secureboot/PK.key
  when: _secureboot_keys.changed

- name: Sign /boot/*
  ansible.builtin.shell:
    cmd: |-
      sbctl sign -s /boot/EFI/BOOT/BOOTX64.EFI
      sbctl sign -s /boot/EFI/systemd/systemd-bootx64.efi
  when: _secureboot_keys.changed

- name: Sign /usr/lib/fwupd/efi/fwupdx64.efi
  ansible.builtin.shell:
    cmd: sbctl sign -s -o /usr/lib/fwupd/efi/fwupdx64.efi.signed /usr/lib/fwupd/efi/fwupdx64.efi
  when: _secureboot_keys.changed

- name: Verify /etc/keys/secureboot
  ansible.builtin.shell:
    cmd: sbctl verify
