---
- name: Install Shell
  community.general.pacman:
    name:
      - starship
      - zsh
    state: present

- name: Install Shell Optionals
  community.general.pacman:
    name:
      - fzf
      - zsh-autocomplete
      - zsh-autosuggestions
      - zsh-completions
      - zsh-syntax-highlighting
    state: present
    reason: dependency