---
- name: Install Shell
  community.general.pacman:
    name:
      - starship
      - zsh
    state: present

- name: Install Shell Optionals
  community.general.pacman:
    name:
      - fzf
      - zsh-autocomplete
      - zsh-autosuggestions
      - zsh-completions
      - zsh-syntax-highlighting
    state: present
    reason: dependency

- name: Configure Shell
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/etc/skel/{{ item | basename | regex_replace('\\.j2', '') }}"
    owner: root
    group: root
    mode: "0644"
  loop: "{{ lookup('fileglob', playbook_dir + '/templates/rules.d/*.rules.j2', wantlist=True) }}"