---
- name: Install TeX Live
  community.general.pacman:
    name:
      - texlive-basic
      - texlive-latex
      - texlive-latexrecommended
      - texlive-latexextra
      - texlive-fontsrecommended
      - texlive-fontsextra
      - texlive-mathscience
    state: present
