---
- name: Install Tools
  community.general.pacman:
    name:
      - alsa-utils
      - arch-audit
      - bind
      - btop
      - btrfs-progs
      - dosfstools
      - e2fsprogs
      - exfatprogs
      - f2fs-tools
      - go
      - gptfdisk
      - ipcalc
      - lshw
      - nmap
      - openbsd-netcat
      - powertop
      - restic
      - tmux
      - usbutils
      - vim
      - wireguard-tools
      - wol
    state: present

- name: Configure /etc/skel/.config/pikaur.conf
  ansible.builtin.template:
    src: "{{ playbook_dir }}/templates/tools/pikaur.conf.j2"
    dest: /etc/skel/.config/pikaur.conf
    owner: root
    group: root
    mode: "0644"

- name: Configure /etc/skel/.tmux.conf
  ansible.builtin.template:
    src: "{{ playbook_dir }}/templates/tools/tmux.conf.j2"
    dest: /etc/skel/.tmux.conf
    owner: root
    group: root
    mode: "0644"

- name: Configure /etc/skel/.vimrc
  ansible.builtin.template:
    src: "{{ playbook_dir }}/templates/tools/vimrc.j2"
    dest: /etc/skel/.vimrc
    owner: root
    group: root
    mode: "0644"
    